### ISSUE TITLE
Package as proper python package

### ISSUE THREAD

**Issue by janbernloehr** [DrMarkusVoss/pumla#1]
If we follow the [python packaging guide](https://packaging.python.org/tutorials/packaging-projects/), then pumla can be easily installed using pip and distributed as a wheel. The latter allows to upload it to pypi and simply install it by `pip install pumla`.

Moreover, this would make pumla feel look and feel like other python packages easing contributions.

**Comment by DrMarkusVoss** [comment]
As pumla relies heavily on PlantUML, and the Python command line tool is only one aspect of the solution, the other is the Preprocessor macros for PlantUML, I am not sure whether it would raise wrong expectations. At least then I should provide an install function that automatically downloads the proper PlantUML version and also trigger the rendering of the diagrams via puma.py.

**Comment by DrMarkusVoss** [comment]
But organizing the repo like that makes sense even when I do not put it on the python package index I guess.

**Comment by janbernloehr** [comment]
Sure. From my pov, `pip install pumla` should only install the cli and make it available. We can add a check if plantuml is installed and provide a link installation instructions if it is missing but I would not do that during `pip install`.

**Comment by DrMarkusVoss** [comment]
updated doc and examples and merged #3 to fix the issue. :-) thank you for your effort @janbernloehr
