### ISSUE TITLE
PUMLAPutRelationsForElement incompatible with C4

### ISSUE THREAD

**Issue by thiblege** [DrMarkusVoss/pumla#46]
**Describe the bug**
If you try to use PUMLAPutRelationsForElement with C4REL, it generate a line like

element1 C4Rel element2 : action

And that's break the plantuml generation.

**Comment by DrMarkusVoss** [comment]
@thiblege thanks for reporting, I'll check.

**Comment by DrMarkusVoss** [comment]
@thiblege big is fixed now.
