### ISSUE TITLE
Provide a descriptive helptext for pumla cli tool

### ISSUE THREAD

**Issue by cbandera** [DrMarkusVoss/pumla#5]
**Is your feature request related to a problem? Please describe.**
Most users are probably used to running a new tool with `--help` to get started. `pumla` only reports version and author in this case. 

**Describe the solution you'd like**
I suggest to use a common library like [argparse](https://docs.python.org/3/howto/argparse.html) to do the argument parsing. It will also generate the necessary code for the `--help` argument for you. Using the library, will probably also help readability of the arg-parsing code in pumla and you might be able to simply move some of the documentation from the user guide directly into the source code. Hence keeping it all cohesive and consistent.

**Describe alternatives you've considered**
None

**Additional context**
-

**Comment by DrMarkusVoss** [comment]
Thanks, yes, this has been neglected so far...

**Comment by DrMarkusVoss** [comment]
closed by mistake...

**Comment by DrMarkusVoss** [comment]
isse solved with #7
